[package]
name = "git-cliff-tui"
version = "2.5.0" # managed by release.sh
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
md-tui = { path = "../../md-tui" }

[dependencies.git-cliff-core]
version = "2.5.0" # managed by release.sh
path = "../git-cliff-core"
